name: Build and Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  build-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, contest-service, submission-service, execution-service, scoring-service, leaderboard-service]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./services/${{ matrix.service }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend/nextjs-app
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/codeforces-frontend:latest,${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/codeforces-frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Kubernetes
      run: |
        # Configure kubeconfig for Azure AKS
        az aks get-credentials --resource-group codeforces-rg --name codeforces-aks-cluster
        
        # Update image tags in deployments
        kubectl set image deployment/frontend frontend=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/codeforces-frontend:latest -n codeforces || true
        kubectl set image deployment/auth-service auth-service=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/auth-service:latest -n codeforces || true
        kubectl set image deployment/contest-service contest-service=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/contest-service:latest -n codeforces || true
        kubectl set image deployment/submission-service submission-service=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/submission-service:latest -n codeforces || true
        kubectl set image deployment/execution-service execution-service=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/execution-service:latest -n codeforces || true
        kubectl set image deployment/scoring-service scoring-service=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/scoring-service:latest -n codeforces || true
        kubectl set image deployment/leaderboard-service leaderboard-service=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/leaderboard-service:latest -n codeforces || true
        
        # Wait for rollout
        kubectl rollout status deployment/frontend -n codeforces --timeout=3m
